apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stolon.fullname" . }}-alerts
  labels:
    app: {{ include "stolon.name" . }}
    chart: {{ include "stolon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (.Files.Glob "alerts/*").AsConfig | indent 2 }}
