{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "stolon.fullname" . }}:crd
  labels:
    app: {{ template "stolon.name" . }}
    chart: {{ template "stolon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    verbs:
      - "*"
    resources:
      - customresourcedefinitions
  - apiGroups:
      - stolon.gravitational.io
    verbs:
      - "*"
    resources:
      - stolonupgrades
{{- end -}}
