apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stolon.fullname" . }}-cluster-config
  labels:
    app: {{ include "stolon.name" . }}
    chart: {{ include "stolon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  cluster-config.json: |
    {{ toJson .Values.clusterSpec }}
