{{ if and .Release.IsInstall .Values.job.autoCreateCluster }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "stolon.fullname" . }}-create-cluster
  labels:
    app: {{ template "stolon.name" . }}
    chart: {{ template "stolon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 60000
  template:
    metadata:
      labels:
        app: {{ template "stolon.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      nodeSelector:
        gravitational.io/k8s-role: "master"
      restartPolicy: OnFailure
      serviceAccountName: {{ template "stolon.serviceAccountName" . }}
      containers:
        - name: {{ template "stolon.fullname" . }}-create-cluster
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/dumb-init", "--", "/bin/bash", "-exc"]
          args:
            - |
              stolonctl init --yes '{ "initMode": "new", {{ template "stolon.clusterSpec" . }} }'
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: STOLONCTL_CLUSTER_NAME
              value: {{ template "stolon.clusterName" . }}
            - name: STOLONCTL_STORE_BACKEND
              value: {{ .Values.store.backend | quote }}
            {{- if or (eq .Values.store.backend "etcdv2") (eq .Values.store.backend "etcdv3") }}
            - name: STOLONCTL_STORE_ENDPOINTS
              value: "https://$(NODE_NAME):2379"
            {{- end }}
            {{- if not (empty .Values.store.caFile) }}
            - name: STOLONCTL_STORE_CA_FILE
              value: {{ .Values.store.caFile | quote }}
            {{- end }}
            {{- if not (empty .Values.store.certFile) }}
            - name: STOLONCTL_STORE_CERT_FILE
              value: {{ .Values.store.certFile | quote }}
            {{- end }}
            {{- if not (empty .Values.store.key) }}
            - name: STOLONCTL_STORE_KEY
              value: {{ .Values.store.key | quote }}
            {{- end }}
            - name: STOLONCTL_DEBUG
              value: {{ .Values.debug | quote }}
          {{- with .Values.keeper.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.keeper.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
