apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "stolon.fullname" . }}-keeper
  labels:
    app: {{ template "stolon.name" . }}
    product: {{ template "stolon.name" . }}
    chart: {{ template "stolon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    stolon-keeper: "yes"
    name: stolon-keeper
spec:
  serviceName: {{ template "stolon.fullname" . }}-keeper-headless
  replicas: {{ .Values.keeper.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "stolon.name" . }}
      release: {{ .Release.Name }}
      component: stolon-keeper
      name: stolon-keeper
  template:
    metadata:
      labels:
        app: {{ template "stolon.name" . }}
        product: {{ template "stolon.name" . }}
        release: {{ .Release.Name }}
        component: stolon-keeper
        stolon-cluster: {{ template "stolon.clusterName" . }}
        stolon-keeper: "yes"
        name: stolon-keeper
    spec:
      serviceAccountName: {{ template "stolon.serviceAccountName" . }}
      {{- with .Values.keeper.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 15
      initContainers:
        - name: fix-permissions
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/dumb-init", "--", "/usr/local/bin/init-container.sh"]
          securityContext:
            runAsUser: 0
          {{- with .Values.keeper.initVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      containers:
        {{- if or (eq .Values.store.backend "etcdv2") (eq .Values.store.backend "etcdv3") }}
        - name: etcd
          image: "{{ .Values.etcdImage.repository }}:{{ .Values.etcdImage.tag }}"
          imagePullPolicy: {{ .Values.etcdImage.pullPolicy }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ETCD_ENDPOINTS
              value: "$(NODE_NAME):2379"
            - name: ETCD_LISTEN_ADDR
              value: "127.0.0.1:2379"
            {{- if not (empty .Values.store.caFile) }}
            - name: ETCD_TRUSTED_CA_FILE
              value: {{ .Values.store.caFile | quote }}
            {{- end }}
          {{- with .Values.keeper.etcdVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        - name: keeper
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/dumb-init", "--", "/bin/bash", "-exc"]
          args:
            - |
              export STKEEPER_UID={{ .Values.keeper.uid_prefix }}${POD_NAME: -1}
              stolon-keeper
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STKEEPER_CLUSTER_NAME
              value: {{ template "stolon.clusterName" . }}
            - name: STKEEPER_STORE_BACKEND
              value: {{ .Values.store.backend | quote }}
            {{- if not (empty .Values.store.endpoints) }}
            - name: STKEEPER_STORE_ENDPOINTS
              value: {{ .Values.store.endpoints | quote}}
            {{- end }}
            {{- if not (empty .Values.store.caFile) }}
            - name: STKEEPER_STORE_CA_FILE
              value: {{ .Values.store.caFile | quote }}
            {{- end }}
            {{- if not (empty .Values.store.certFile) }}
            - name: STKEEPER_STORE_CERT_FILE
              value: {{ .Values.store.certFile | quote }}
            {{- end }}
            {{- if not (empty .Values.store.key) }}
            - name: STKEEPER_STORE_KEY
              value: {{ .Values.store.key | quote }}
            {{- end }}
            - name: STKEEPER_PG_SU_USERNAME
              value: {{ .Values.superuser.username | quote }}
            - name: STKEEPER_PG_SU_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.existingSecret }}
                  name: {{ .Values.existingSecret | quote }}
                  {{- else }}
                  name: {{ template "stolon.fullname" . }}
                  {{- end }}
                  key: "password"
            - name: STKEEPER_PG_REPL_USERNAME
              value: {{ .Values.replication.username | quote }}
            - name: STKEEPER_PG_REPL_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.existingSecret }}
                  name: {{ .Values.existingSecret | quote }}
                  {{- else }}
                  name: {{ template "stolon.fullname" . }}
                  {{- end }}
                  key: "pg_repl_password"
            - name: STKEEPER_DATA_DIR
              value: {{ .Values.keeper.dataDir | quote }}
            - name: STKEEPER_PG_LISTEN_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: STKEEPER_DEBUG
              value: {{ .Values.debug | quote}}
          ports:
            {{- range $key, $value := .Values.ports }}
            - name: {{ $key }}
              {{ toYaml $value | nindent 14 }}
            {{- end }}
          {{- with .Values.keeper.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.keeper.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
