apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "stolon.fullname" . }}-proxy
  labels:
    app: {{ template "stolon.name" . }}
    chart: {{ template "stolon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: stolon-proxy
    name: stolon-proxy
spec:
  replicas: {{ .Values.proxy.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "stolon.name" . }}
      release: {{ .Release.Name }}
      component: stolon-proxy
      name: stolon-proxy
  template:
    metadata:
      labels:
        app: {{ template "stolon.name" . }}
        release: {{ .Release.Name }}
        component: stolon-proxy
        stolon-cluster: {{ template "stolon.fullname" . }}
        name: stolon-proxy
        product: {{ template "stolon.name" . }}
    spec:
      serviceAccountName: {{ template "stolon.serviceAccountName" . }}
      {{- with .Values.proxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- if or (eq .Values.store.backend "etcdv2") (eq .Values.store.backend "etcdv3") }}
        - name: etcd
          image: "{{ .Values.etcdImage.repository }}:{{ .Values.etcdImage.tag }}"
          imagePullPolicy: {{ .Values.etcdImage.pullPolicy }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ETCD_ENDPOINTS
              value: "$(NODE_NAME):2379"
            - name: ETCD_LISTEN_ADDR
              value: "127.0.0.1:2379"
            {{- if not (empty .Values.store.caFile) }}
            - name: ETCD_TRUSTED_CA_FILE
              value: {{ .Values.store.caFile | quote }}
            {{- end }}
          {{- with .Values.proxy.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        - name: proxy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/dumb-init", "--", "stolon-proxy"]
          env:
            - name: STPROXY_CLUSTER_NAME
              value: {{ template "stolon.clusterName" . }}
            - name: STPROXY_STORE_BACKEND
              value: {{ .Values.store.backend | quote}}
            {{- if not (empty .Values.store.endpoints) }}
            - name: STPROXY_STORE_ENDPOINTS
              value: {{ .Values.store.endpoints | quote}}
            {{- end }}
            {{- if not (empty .Values.store.caFile) }}
            - name: STPROXY_STORE_CA_FILE
              value: {{ .Values.store.caFile | quote }}
            {{- end }}
            {{- if not (empty .Values.store.certFile) }}
            - name: STPROXY_STORE_CERT_FILE
              value: {{ .Values.store.certFile | quote }}
            {{- end }}
            {{- if not (empty .Values.store.key) }}
            - name: STPROXY_STORE_KEY
              value: {{ .Values.store.key | quote }}
            {{- end }}
            - name: STPROXY_LISTEN_ADDRESS
              value: {{ .Values.proxy.listenAddress | default "0.0.0.0" | quote }}
            - name: STPROXY_METRICS_LISTEN_ADDRESS
              value: "0.0.0.0:{{ .Values.ports.metrics.containerPort }}"
            - name: STPROXY_DEBUG
              value: {{ .Values.debug | quote}}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.ports.stolon.containerPort }}
            initialDelaySeconds: 10
            timeoutSeconds: 5
          ports:
          {{- range $key, $value := .Values.ports }}
            - name: {{ $key }}
              {{- toYaml $value | nindent 14 }}
          {{- end }}
          {{- with .Values.proxy.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.proxy.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
