{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "stolon.fullname" . }}
  labels:
    app: {{ template "stolon.name" . }}
    chart: {{ template "stolon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - privileged
    verbs:
      - use
  - apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
    resources:
      - secrets
    resourceNames:
      - stolon
      - cluster-ca
      - cluster-default-ssl
  - apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
    resources:
      - configmaps
      - endpoints
      - events
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - services
      - jobs
  - apiGroups:
      - extensions
      - apps
    verbs:
      - delete
    resources:
      - deployments
      - daemonsets
    resourceNames:
      - "stolon-sentinel"
      - "stolon-keeper"
  - apiGroups:
      - batch
      - extensions
    verbs:
      - "*"
    resources:
      - jobs
{{- end -}}
