apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stolon.fullname" . }}-telegraf
  labels:
    app: {{ include "stolon.name" . }}
    chart: {{ include "stolon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  telegraf.conf: |+
    {{ template "telegraf_global_tags" .Values.telegraf.config.global_tags }}
    {{ template "telegraf_agent" .Values.telegraf.config.agent }}
    {{ template "telegraf_processors" .Values.telegraf.config.processors }}
    {{ template "telegraf_outputs" .Values.telegraf.config.outputs }}
    {{ template "telegraf_inputs" .Values.telegraf.config.inputs -}}
