apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "stolon.fullname" . }}-telegraf
  labels:
    app: {{ include "stolon.name" . }}
    chart: {{ include "stolon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  endpoints:
  - interval: 60s
    port: {{ .Values.telegraf.service.name }}
  selector:
    matchLabels:
      component: {{ template "stolon.fullname" . }}-telegraf
