# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#

ignored = ["github.com/gravitational/stolon-app/images*", "github.com/Sirupsen/logrus"]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"
  source = "github.com/gravitational/logrus"

[[constraint]]
  name = "github.com/gravitational/rigging"
  version = "0.0.10"

[[override]]
  name = "k8s.io/api"
  branch = "release-1.9"

[[override]]
  name = "github.com/coreos/etcd"
  version = "~3.0.0"

[[override]]
  name = "k8s.io/kubernetes"
  branch = "release-1.9"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.9"

[[override]]
  name = "github.com/ugorji/go"
  revision = "f1f1a805ed361a0e078bb537e4ea78cd37dcf065"

[[constraint]]
  name = "github.com/gravitational/stolon"
  version = "0.3.0"

[[override]]
  name = "github.com/minio/minio-go"
  version = "~2.0"
