apiVersion: v1
kind: Application
metadata:
  repository: gravitational.io
  name: stolon-app
  resourceVersion: 0.0.1
  namespace: default
base: gravitational.io/k8s-aws:0.0.0+latest
service_labels:
  stolon-postgres: "yes"
installer:
  provisioners:
    virsh:
      variables:
        devices:
          - device: vdb
            mb: 8000
  servers:
    node:
      cpu:
        min_count: 2
      description: "stolon server"
      labels:
        role: "node"
        stolon-keeper: "yes"
      ram:
        min_total_mb: 2000
      directories:
        - name: /var/lib/gravity
          min_total_mb: 4000
      mounts:
        - name: stolon-data
          source: /var/lib/data/stolon
          destination: /var/lib/data/stolon
          create_if_missing: true
      instance_types:
        aws_terraform:
          - m3.large
          - m3.xlarge
          - c3.large
          - c3.xlarge
          - c3.2xlarge
          - c3.4xlarge
          - i2.xlarge
          - i2.2xlarge
  flavors:
    title: "Select a flavor"
    items:
      - name: "single"
        description: "1 node"
        threshold:
          value: 1
          label: "1"
        profiles:
          node: 1
      - name: "triple"
        description: "3 nodes"
        threshold:
          value: 3
          label: "3"
        profiles:
          node: 3
hooks:
  install:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: stolon-app-install
      spec:
        template:
          metadata:
            name: stolon-app-install
          spec:
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: stolon-bootstrap:latest
  update:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: stolon-app-update
      spec:
        template:
          metadata:
            name: stolon-app-update
          spec:
            restartPolicy: OnFailure
            containers:
              - name: update
                image: stolon-update:latest
  uninstall:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: stolon-app-uninstall
      spec:
        template:
          metadata:
            name: stolon-app-uninstall
          spec:
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: stolon-uninstall:latest
