apiVersion: v1
kind: Application
metadata:
  repository: gravitational.io
  name: stolon-app
  resourceVersion: 0.0.1
  namespace: default
base: gravitational.io/k8s-aws:0.0.0+latest
service_labels:
  stolon-postgres: "yes"
installer:
  provisioners:
    virsh:
      variables:
        devices:
          - device: vdb
            mb: 8000
  servers:
    node:
      cpu:
        min_count: 2
      min_count: 3
      description: "stolon server"
      labels:
        role: "node"
        stolon-keeper: "yes"
      ram:
        min_total_mb: 2000
      directories:
        - name: /var/lib/gravity
          min_total_mb: 4000
      mounts:
        - source: /var/lib/data/stolon
          destination: /var/lib/data/stolon
          create_if_missing: true
hooks:
  install:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: stolon-app-install
      spec:
        template:
          metadata:
            name: stolon-app-install
          spec:
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: stolon-bootstrap:latest
  update:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: stolon-app-update
      spec:
        template:
          metadata:
            name: stolon-app-update
          spec:
            restartPolicy: OnFailure
            containers:
              - name: update
                image: stolon-update:latest
  uninstall:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: stolon-app-uninstall
      spec:
        template:
          metadata:
            name: stolon-app-uninstall
          spec:
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: stolon-uninstall:latest
