apiVersion: v1
kind: Application
metadata:
  namespace: default
  name: stolon-app
  resourceVersion: 0.0.1
base: gravitational.io/k8s-aws:1.2.3
hooks:
  install:
    containerImage: stolon-bootstrap:0.0.1
  uninstall:
    containerImage: stolon-uninstall:0.0.1
installer:
  provisioners:
    virsh:
      variables:
        devices:
          - device: vdb
            mb: 4096
  servers:
    node:
      min_count: 2
      description: "stolon sentinel server"
      labels:
        role: node
      cpu:
        min_count: 1
      ram:
        min_total_mb: 1000
      directories:
        - name: /var/gravity
          min_total_mb: 4096
          fs_types: ['btrfs']
      mounts:
        - source: /var/stolon-data
          destination: /stolon-data
          create_if_missing: true
