apiVersion: v1
kind: Application
metadata:
  repository: gravitational.io
  name: stolon-app
  resourceVersion: "0.0.4"
  namespace: default
service_labels:
  stolon-postgres: stolon-postgres
base: gravitational.io/k8s-aws:1.3.0-1
installer:
  provisioners:
    virsh:
      variables:
        devices:
          - device: vdb
            mb: 8000
  servers:
    master:
      cpu:
        min_count: 1
      ram:
        min_total_mb: 2000
    node:
      cpu:
        min_count: 1
      min_count: 2
      description: "stolon server"
      labels:
        role: node
        stolon-keeper: stolon-keeper
      ram:
        min_total_mb: 2000
      directories:
        - name: /var/lib/gravity
          min_total_mb: 4000
          fs_types: ["xfs", "btrfs"]
      mounts:
        - source: /var/lib/data/stolon
          destination: /var/lib/data/stolon
          create_if_missing: true
hooks:
  install:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: stolon-app-install
      spec:
        template:
          metadata:
            name: stolon-app-install
          spec:
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: stolon-bootstrap:0.0.1
  uninstall:
    spec:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: stolon-app-uninstall
      spec:
        template:
          metadata:
            name: stolon-app-uninstall
          spec:
            restartPolicy: OnFailure
            containers:
              - name: bootstrap
                image: stolon-uninstall:0.0.1
