---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stolon-backup
---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: Role
metadata:
  name: stolon-backup
  namespace: default
rules:
  - apiGroups:
      -  ""
    verbs:
      - get
      - list
      - watch
    resources:
      - secrets
    resourceNames:
      - stolon
  - apiGroups:
      -  ""
    verbs:
      - get
      - list
      - watch
    resources:
      - configmaps
      - endpoints
      - events
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - services
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: stolon-backup
subjects:
  - kind: ServiceAccount
    name: stolon-backup
    namespace: default
roleRef:
  kind: Role
  name: stolon-backup
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: stolon-backup
spec:
  template:
    metadata:
      name: stolon-backup
    spec:
      serviceAccountName: stolon-backup
      containers:
      - name: backup
        image: apiserver:5000/stolon:latest
        args: ["db", "backup", "{{STOLON_BACKUP_DB}}", "/backups"]
        env:
          - name: CTL
            value: "true"
          - name: STOLONCTL_DB_USERNAME
            value: "stolon"
          - name: STOLON_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: stolon
                key: password
        volumeMounts:
          - mountPath: /backups
            name: backups
      volumes:
        - name: backups
          hostPath:
            path: /var/backups
      restartPolicy: OnFailure
