apiVersion: batch/v1
kind: Job
metadata:
  name: stolon-backup
spec:
  template:
    metadata:
      name: stolon-backup
    spec:
      containers:
      - name: backup
        imagePullPolicy: Always
        image: apiserver:5000/stolonctl:0.0.5
        command: ["stolonctl", "db", "backup", "postgres", "/backups", "--host", "$STOLON_POSTGRES_SERVICE_HOST" , "--port" , "$STOLON_POSTGRES_SERVICE_PORT", "--username", "stolon"]
        volumeMounts:
          - mountPath: /backups
            name: backups
          - mountPath: /etc/secrets/stolon
            name: stolon
      volumes:
        - name: backups
          hostPath:
            path: /var/backups
        - name: stolon
          secret:
            secretName: stolon
      restartPolicy: OnFailure
