apiVersion: batch/v1
kind: Job
metadata:
  name: stolon-backup
spec:
  template:
    metadata:
      name: stolon-backup
    spec:
      containers:
      - name: backup
        imagePullPolicy: Always
        image: apiserver:5000/stolon:latest
        args: ["db", "backup", "{{STOLON_BACKUP_DB}}", "/backups"]
        env:
          - name: STOLONCTL_DB_USERNAME
            value: "stolon"
          - name: CTL
            value: "true"
        volumeMounts:
          - mountPath: /backups
            name: backups
          - mountPath: /etc/secrets/stolon
            name: stolon
      volumes:
        - name: backups
          hostPath:
            path: /var/backups
        - name: stolon
          secret:
            secretName: stolon
      restartPolicy: OnFailure
