---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stolon-deletedb
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: Role
metadata:
  name: stolon-deletedb
  namespace: default
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - privileged
    verbs:
      - use
  - apiGroups:
      -  ""
    verbs:
      - get
      - list
      - watch
    resources:
      - secrets
    resourceNames:
      - stolon
  - apiGroups:
      -  ""
    verbs:
      - get
      - list
      - watch
    resources:
      - configmaps
      - endpoints
      - events
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - services
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: stolon-deletedb
  namespace: default
subjects:
  - kind: ServiceAccount
    name: stolon-deletedb
    namespace: default
roleRef:
  kind: Role
  name: stolon-deletedb
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: stolon-deletedb
  namespace: default
spec:
  template:
    metadata:
      name: stolon-deletedb
      namespace: default
    spec:
      serviceAccount: stolon-deletedb
      securityContext:
        runAsUser: 0
      containers:
      - name: deletedb
        image: apiserver:5000/stolon:latest
        args: ["db", "delete", "{{STOLON_DELETE_DB}}"]
        env:
          - name: CTL
            value: "true"
          - name: STOLONCTL_DB_USERNAME
            value: "stolon"
          - name: STOLON_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: stolon
                key: password
      restartPolicy: OnFailure
