---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stolon-pgbouncer
  namespace: default
data:
  pgbouncer.ini: |
    [databases]
    * = host=PG_SERVICE port=PG_PORT auth_user=stolon

    [pgbouncer]
    user = stolon
    listen_port = 6432
    listen_addr = *
    auth_type = md5
    auth_file = /home/stolon/pgbouncer/users.txt
    auth_query = SELECT * from public.user_lookup($1)
    pidfile = /tmp/pgbouncer.pid
    unix_socket_dir = /tmp
    logfile = /dev/stdout
    admin_users = stolon
    stats_users = stolon
    default_pool_size = DEFAULT_POOL_SIZE
    max_client_conn = MAX_CLIENT_CONN
    max_db_connections = MAX_DB_CONNECTIONS
    min_pool_size = MIN_POOL_SIZE
    pool_mode = POOL_MODE
    reserve_pool_size = RESERVE_POOL_SIZE
    reserve_pool_timeout = RESERVE_POOL_TIMEOUT
    query_timeout = QUERY_TIMEOUT
    ignore_startup_parameters = IGNORE_STARTUP_PARAMETERS
    server_round_robin = 1
    client_tls_sslmode = CLIENT_TLS_SSLMODE
    client_tls_key_file = CLIENT_TLS_KEY_FILE
    client_tls_cert_file = CLIENT_TLS_CERT_FILE
    client_tls_ca_file = CLIENT_TLS_CA_FILE
    client_tls_protocols = CLIENT_TLS_PROTOCOLS
    server_tls_sslmode = SERVER_TLS_SSLMODE
    server_tls_ca_file = SERVER_TLS_CA_FILE
    server_tls_key_file = SERVER_TLS_KEY_FILE
    server_tls_cert_file = SERVER_TLS_CERT_FILE
    server_tls_protocols = SERVER_TLS_PROTOCOLS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stolon-pgbouncer
  namespace: default
  labels:
    component: pgbouncer
    product: stolon
spec:
  selector:
    matchLabels:
      product: stolon
      component: pgbouncer
  replicas: 2
  template:
    metadata:
      namespace: default
      labels:
        component: pgbouncer
        product: stolon
    spec:
      serviceAccountName: stolon
      initContainers:
        - name: fix-secrets
          image: quay.io/gravitational/stolon-pgbouncer:latest
          command: ["/usr/bin/dumb-init", "--", "/usr/local/bin/init-container.sh"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: cluster-ca
              mountPath: /etc/secrets/cluster-ca
            - name: cluster-default
              mountPath: /etc/secrets/cluster-default
            - name: stolon-secrets
              mountPath: /home/stolon/secrets
      containers:
        - name: pgbouncer
          image: stolon-pgbouncer:latest
          args: ["pgbouncer"]
          env:
            - name: PG_SERVICE
              value: "stolon-postgres.default.svc"
            - name: PG_USERNAME
              value: "stolon"
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stolon
                  key: password
            - name: MAX_CLIENT_CONN
              value: "1000"
            - name: SERVER_TLS_SSLMODE
              value: "require"
            - name: SERVER_TLS_CERT_FILE
              value: "/home/stolon/secrets/pgbouncer.pem"
            - name: SERVER_TLS_KEY_FILE
              value: "/home/stolon/secrets/pgbouncer-key.pem"
          volumeMounts:
            - name: pgbouncer-config
              mountPath: /etc/pgbouncer
            - name: stolon-secrets
              mountPath: /home/stolon/secrets
      volumes:
        - name: stolon-secrets
          emptyDir: {}
        - name: cluster-ca
          secret:
            secretName: cluster-ca
        - name: cluster-default
          secret:
            secretName: cluster-default-ssl
        - name: pgbouncer-config
          configMap:
            name: stolon-pgbouncer
---
apiVersion: v1
kind: Service
metadata:
  name: stolon-pgbouncer
  namespace: default
  labels:
    product: stolon
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 6432
  selector:
    component: pgbouncer
    product: stolon
---
apiVersion: batch/v1
kind: Job
metadata:
  name: bootstrap-auth-function
  namespace: default
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: bootstrap-auth-function
    spec:
      restartPolicy: OnFailure
      containers:
        - name: bootstrap
          image: stolon-pgbouncer:latest
          args: ["bootstrap"]
          env:
            - name: PG_SERVICE
              value: "stolon-postgres.default.svc"
            - name: PG_USERNAME
              value: "stolon"
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stolon
                  key: password

