---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-hardening
  namespace: default
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: postgres-hardening
    spec:
      restartPolicy: OnFailure
      containers:
        - name: postgres-hardening
          image: stolon:latest
          command: ["/usr/bin/dumb-init", "--", "/usr/local/bin/stolon-security.sh"]
          env:
            - name: PG_SERVICE
              value: "stolon-postgres.default.svc"
            - name: PG_USERNAME
              value: "stolon"
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stolon
                  key: password
