apiVersion: v1
kind: Service
metadata:
  name: stolon-postgres
  labels:
    stolon-postgres: stolon-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    stolon-proxy: "true"
    stolon-cluster: "kube-stolon"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: stolon-proxy
spec:
  replicas: 1
  selector:
    name: stolon-proxy
  template:
    metadata:
      labels:
        name: stolon-proxy
        stolon-cluster: "kube-stolon"
        stolon-proxy: "true"
    spec:
      containers:
      - name: stolon-proxy
        image: apiserver:5000/stolon:0.2.0
        imagePullPolicy: Always
        env:
          - name: PROXY
            value: "true"
          - name: STPROXY_CLUSTER_NAME
            value: "kube-stolon"
          - name: STPROXY_STORE_BACKEND
            value: "etcd" # Or consul
          - name: STPROXY_STORE_ENDPOINTS
            value: "127.0.0.1:2379"
          - name: STPROXY_STORE_CACERT
            value: "/etc/etcd/secrets/root.cert"
          - name: STPROXY_STORE_CERT
            value: "/etc/etcd/secrets/etcd.cert"
          - name: STPROXY_STORE_KEY
            value: "/etc/etcd/secrets/etcd.key"
            # Enable debugging
          - name: STPROXY_DEBUG
            value: "false"
        ports:
          - containerPort: 5432
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
          - mountPath: /etc/etcd/secrets
            name: etcd-secrets
      volumes:
        - name: etcd-secrets
          hostPath:
            path: /var/state
      hostNetwork: true
