apiVersion: v1
kind: Pod
metadata:
  name: phony
  namespace: default
spec:
  containers:
    - name: phony-bootstrap
      image: stolon-bootstrap:0.0.1
    - name: phony-uninstall
      image: stolon-uninstall:0.0.1
    - name: phony-etcd
      image: quay.io/coreos/etcd:v2.3.6
    - name: phony-stolon
      image: sorintlab/stolon:master
