apiVersion: batch/v1
kind: Job
metadata:
  name: stolon-restore
spec:
  template:
    metadata:
      name: stolon-restore
    spec:
      containers:
      - name: restore
        imagePullPolicy: Always
        image: apiserver:5000/stolon:latest
        args: ["db", "restore", "{{STOLON_BACKUP_FILE}}"]
        env:
          - name: CTL
            value: "true"
          - name: STOLONCTL_DB_USERNAME
            value: "stolon"
          - name: STOLON_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: stolon
                key: password
        volumeMounts:
          - mountPath: /backups
            name: backups
      volumes:
        - name: backups
          hostPath:
            path: /var/backups
      restartPolicy: OnFailure
