---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stolon-restore
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: Role
metadata:
  name: stolon-restore
  namespace: default
rules:
  - apiGroups:
      -  ""
    verbs:
      - get
      - list
      - watch
    resources:
      - secrets
    resourceNames:
      - stolon
  - apiGroups:
      -  ""
    verbs:
      - get
      - list
      - watch
    resources:
      - configmaps
      - endpoints
      - events
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - services
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: stolon-restore
  namespace: default
subjects:
  - kind: ServiceAccount
    name: stolon-restore
    namespace: default
roleRef:
  kind: Role
  name: stolon-restore
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: stolon-restore
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: stolon-restore
        namespace: default
    spec:
      serviceAccountName: stolon-restore
      nodeSelector:
        stolon-keeper: "yes"
      containers:
      - name: restore
        image: apiserver:5000/stolon-restore:latest
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: pithos-keys
                key: tenant.key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: pithos-keys
                key: tenant.secret
          - name: STOLON_USERNAME
            value: stolon
          - name: STOLON_PASSWORD
            valueFrom:
              secretKeyRef:
                name: stolon
                key: password
          - name: PITHOS_S3_ENDPOINT
            value: "pithos.default.svc"
          - name: PITHOS_BACKUP_BUCKET
            value: "stolon-backup"
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
          - name: kubectl
            mountPath: /usr/bin/kubectl
          - name: etcdctl
            mountPath: /usr/bin/etcdctl
          - name: etcd-secrets
            mountPath: /etc/etcd/secrets
          - name: resources
            mountPath: /var/lib/gravity/resources
      volumes:
        - name: kubectl
          hostPath:
            path: /usr/bin/kubectl
        - name: etcdctl
          hostPath:
            path: /usr/bin/etcdctl
        - name: etcd-secrets
          hostPath:
            path: /var/state
        - name: resources
          hostPath:
            path: /var/lib/gravity/local/packages/unpacked/gravitational.io/stolon-app
