---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stolon-rpc
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: stolon-rpc
  namespace: default
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - privileged
    verbs:
      - use
  - apiGroups:
      -  ""
    verbs:
      - get
      - list
      - watch
    resources:
      - secrets
    resourceNames:
      - stolon
      - cluster-ca
      - cluster-default-ssl
  - apiGroups:
      -  ""
    verbs:
      - get
      - list
      - watch
    resources:
      - configmaps
      - endpoints
      - events
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - services
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: stolon-rpc
  namespace: default
subjects:
  - kind: ServiceAccount
    name: stolon-rpc
    namespace: default
roleRef:
  kind: Role
  name: stolon-rpc
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: stolon-rpc
  namespace: default
  labels:
    stolon-rpc: "yes"
    product: stolon
spec:
  type: ClusterIP
  ports:
    - port: 5973
      targetPort: 5973
  selector:
    stolon-rpc: "yes"
    stolon-cluster: "kube-stolon"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stolon-rpc
  namespace: default
spec:
  selector:
    matchLabels:
      name: stolon-rpc
      stolon-rpc: "yes"
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        name: stolon-rpc
        namespace: default
        stolon-cluster: "kube-stolon"
        stolon-rpc: "yes"
        component: rpc
        product: stolon
    spec:
      serviceAccountName: stolon-rpc
      securityContext:
        runAsUser: 0
      nodeSelector:
        stolon-keeper: "yes"
      containers:
      - name: rpc
        image: stolon:latest
        volumeMounts:
          - mountPath: /usr/local/bin/kubectl
            name: kubectl
        env:
          - name: RPC
            value: "true"
          - name: STOLONRPC_LOG_LEVEL
            value: "debug"
          - name: STOLONRPC_PORT
            value: "5973"
          - name: STOLONRPC_DB_USERNAME
            value: "stolon"
          - name: STOLON_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: stolon
                key: password
        ports:
          - containerPort: 5973
        readinessProbe:
          tcpSocket:
            port: 5973
          initialDelaySeconds: 10
          timeoutSeconds: 5
      volumes:
        - hostPath:
            path: /usr/bin/kubectl
          name: kubectl
