apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stolon-utils
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: stolon-utils
        stolon-cluster: "kube-stolon"
        stolon-utils: "yes"
        app: stolon
        component: utils
    spec:
      nodeSelector:
        stolon-keeper: "yes"
      containers:
      - name: utils
        image: apiserver:5000/stolon-telegraf:latest
        env:
          - name: STOLON_USERNAME
            value: "stolon"
          - name: STOLON_PASSWORDFILE
            value: "/etc/secrets/stolon/password"
          - name: INFLUXDB_TELEGRAF_USERNAME
            valueFrom:
              secretKeyRef:
                name: telegraf-influxdb-creds
                key: username
          - name: INFLUXDB_TELEGRAF_PASSWORD
            valueFrom:
              secretKeyRef:
                name: telegraf-influxdb-creds
                key: password
        volumeMounts:
          - name: secrets
            mountPath: /etc/secrets/stolon
          - name: gravity-log
            mountPath: /var/log
      volumes:
        - name: gravity-log
          hostPath:
            path: /var/log/gravity
        - name: secrets
          secret:
            secretName: stolon
