---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stolon-utils
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: stolon-utils
  namespace: default
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - privileged
    verbs:
      - use
  - apiGroups:
      -  ""
    verbs:
      - get
      - list
      - watch
    resources:
      - secrets
    resourceNames:
      - stolon
  - apiGroups:
      -  ""
    verbs:
      - get
      - list
      - watch
    resources:
      - configmaps
      - endpoints
      - events
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - services
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: stolon-utils
  namespace: default
subjects:
  - kind: ServiceAccount
    name: stolon-utils
    namespace: default
roleRef:
  kind: Role
  name: stolon-utils
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stolon-utils
  namespace: default
spec:
  selector:
    matchLabels:
      name: stolon-utils
      stolon-utils: "yes"
  replicas: 1
  template:
    metadata:
      namespace: default
      labels:
        name: stolon-utils
        namespace: default
        stolon-cluster: "kube-stolon"
        stolon-utils: "yes"
        component: utils
        product: stolon
    spec:
      serviceAccountName: stolon-utils
      securityContext:
        runAsUser: 0
      nodeSelector:
        stolon-keeper: "yes"
      containers:
      - name: utils
        image: stolon-telegraf:latest
        env:
          - name: STOLON_USERNAME
            value: "stolon"
          - name: STOLON_PASSWORDFILE
            value: "/etc/secrets/stolon/password"
          - name: INFLUXDB_TELEGRAF_USERNAME
            valueFrom:
              secretKeyRef:
                name: telegraf-influxdb-creds
                key: username
          - name: INFLUXDB_TELEGRAF_PASSWORD
            valueFrom:
              secretKeyRef:
                name: telegraf-influxdb-creds
                key: password
        volumeMounts:
          - name: secrets
            mountPath: /etc/secrets/stolon
          - name: gravity-log
            mountPath: /var/log
      volumes:
        - name: gravity-log
          hostPath:
            path: /var/log/gravity
        - name: secrets
          secret:
            secretName: stolon
