---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stolon-utils
---
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: Role
metadata:
  name: stolon-utils
  namespace: default
rules:
  - apiGroups:
      -  ""
    verbs:
      - get
      - list
      - watch
    resources:
      - secrets
    resourceNames:
      - stolon
  - apiGroups:
      -  ""
    verbs:
      - get
      - list
      - watch
    resources:
      - configmaps
      - endpoints
      - events
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - services
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: stolon-utils
subjects:
  - kind: ServiceAccount
    name: stolon-utils
    namespace: default
roleRef:
  kind: Role
  name: stolon-utils
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stolon-utils
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: stolon-utils
        stolon-cluster: "kube-stolon"
        stolon-utils: "yes"
        app: stolon
        component: utils
    spec:
      serviceAccountName: stolon-utils
      nodeSelector:
        stolon-keeper: "yes"
      containers:
      - name: utils
        image: apiserver:5000/stolon-telegraf:latest
        env:
          - name: STOLON_USERNAME
            value: "stolon"
          - name: STOLON_PASSWORDFILE
            value: "/etc/secrets/stolon/password"
        volumeMounts:
          - name: secrets
            mountPath: /etc/secrets/stolon
          - name: gravity-log
            mountPath: /var/log
      volumes:
        - name: gravity-log
          hostPath:
            path: /var/log/gravity
        - name: secrets
          secret:
            secretName: stolon
